services:
  web:
    image: dnviti/anaconda-vscode:latest
    ports:
      - 8080:8080
      - 2222:22
    volumes:
      - work:/work
      - config:/root/.config/code-server

volumes:
  work:
  config:
