services:
  web:
    image: dnviti/anaconda-vscode:latest
    ports:
      - 8080:8080
      - 2222:22
    environment:
      - SSH_USERNAME=${SSH_USERNAME}
      - SSH_PASSWORD=${SSH_PASSWORD}
      - SSH_KEY=${SSH_KEY_CONTENT}
      - PASSWORD=${PASSWORD} # vscode access password
    build:
      context: .
      dockerfile: Dockerfile
